---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dust-server-fe
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - gke.devmode.cloud
    secretName: gke-devmodecloud-tls
  - hosts:
    - blog.gke.devmode.cloud
    - diary.gke.devmode.cloud
    secretName: apps-gke-devmodecloud-tls
  rules:
  - host: gke.devmode.cloud
    http: &http_rules
      paths:
      - path: /
        backend:
          serviceName: dust-server
          servicePort: 80
  - host: blog.gke.devmode.cloud
    http: *http_rules
  - host: gke.devmode.cloud
    http: *http_rules
