apiVersion: apps/v1
kind: Deployment
metadata:
  name: dust-server
  labels:
    app: dust-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dust-server
  template:
    metadata:
      labels:
        app: dust-server
        revision: "3"
    spec:
      containers:
      - name: dust-server
        image: gcr.io/stardust-156404/dust-server:latest
        imagePullPolicy: Always
        args:
        - node
        - nodejs
        - serve
        ports:
        - containerPort: 9238
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9238
          initialDelaySeconds: 5
          periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: dust-server
spec:
  type: NodePort
  selector:
    app: dust-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9238

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dust-server-fe
  annotations:
    kubernetes.io/ingress.global-static-ip-name: dust-server
    networking.gke.io/managed-certificates: devmodecloud-gke
spec:
  backend:
    serviceName: dust-server
    servicePort: 80

---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: devmodecloud-gke
spec:
  domains:
    - gke.devmode.cloud
