apiVersion: apps/v1
kind: Deployment
metadata:
  name: dust-server
  labels:
    app: dust-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dust-server
  template:
    metadata:
      labels:
        app: dust-server
        revision: "1"
    spec:
      containers:
      - name: dust-server
        image: gcr.io/stardust-156404/dust-server:latest
        imagePullPolicy: Always
        args:
        - node
        - nodejs
        - serve
        ports:
        - containerPort: 9238
      nodeSelector:
        cloud.google.com/gke-nodepool: micro

---
apiVersion: v1
kind: Service
metadata:
  name: dust-server
spec:
  type: NodePort
  selector:
    app: dust-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9328

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dust-server-fe
spec:
  backend:
    serviceName: dust-server
    servicePort: 80
