apiVersion: batch/v1
kind: Job
metadata:
  name: push-dust-server
  labels:
    purpose: build
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: docker
        image: gcr.io/stardust-156404/build-shell:latest
        securityContext:
          privileged: true
        args:
        - bash
        - -exc
        - >
          dockerd --host=unix:///var/run/docker.sock &
          git clone https://github.com/stardustapp/dust-server
          ;cd dust-server
          ;GitHash="$(git describe --always --long --dirty)"
          ;ImageTag="gcr.io/stardust-156404/dust-server:$GitHash"
          ;docker build -t $ImageTag .
          ;docker push $ImageTag
          ;kubectl set image deployment.v1.apps/dust-server dust-server=$ImageTag
          ;kubectl delete job push-dust-server &
      restartPolicy: Never
      nodeSelector:
        purpose: build
      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule
  backoffLimit: 1
